### ISSUE TITLE
[Suggestion] Dark, White and Blue theme

### ISSUE THREAD

**Issue by Khornath** [screeps/docs#10]
I personally prefer the dark theme.

although some arg that white theme has better readability, make it so people can switch between themes, while keeping white theme default?

Feel free to make sub suggestions or criticize about my statement.

**Comment by tedivm** [comment]
Meta suggestion- install the Dark Reader extension, or equivalent. Then you can turn any website into a dark site.

**Comment by squished-01** [comment]
I disagree that the white background improves readability.  The sharp contrast between the white background and all the screenshots and charts that still have the gray background hurts the eyes.

**Comment by artch** [comment]
We don't have any plans to support theming natively on the docs site. Feel free to use your own tools to modify it's look&feel though.
