### ISSUE TITLE
OBSTACLE_OBJECT_TYPES is outdated

### ISSUE THREAD

**Issue by thibaut-fagart** [screeps/docs#115]
#ingame
OBSTACLE_OBJECT_TYPES
spawn,creep,source,mineral,controller,constructedWall,extension,link,storage,tower,observer,powerSpawn,powerBank,lab,terminal,nuker

#from docs
OBSTACLE_OBJECT_TYPES: ["spawn", "creep", "wall", "source", "constructedWall", "extension", "link", "storage", "tower", "observer", "powerSpawn", "powerBank", "lab", "terminal","nuker"],

**Comment by o4kapuk** [comment]
It should be fixed now.
