### ISSUE TITLE
Constant reversed : POWER_INFO[PWR_OPERATE_POWER].duration

### ISSUE THREAD

**Issue by ssmith151** [screeps/docs#128]
In the constants section of the docs the POWER_INFO is different than in game.

POWER_INFO[PWR_OPERATE_POWER].duration and cooldown are backwards.

The same may be true for PWR_OPERATE_FACTORY and PWR_OPERATE_CONTROLLER.

**Comment by o4kapuk** [comment]
Should be fixed now, thanks
